### ISSUE TITLE
Widget is not compatible with Customizer or Siteorigin's Pagebuilder

### ISSUE THREAD

**Issue by mathetos** [impress-org/Google-Places-Reviews#1]
## Regarding Customizer

We need to enqueue our widget scripts to load in the Customizer in addition to the Widgets.php page since the Customizer now natively handles widgets as well.
## Regaring Siteorigin Pagebuilder

As seen in this ticket here, our JS is totally borked in their PageBuilder:
https://wordpress.org/support/topic/wont-render-on-page?replies=4#post-7572031

It's a popular and free pagebuilder solution. And they have developer docs for forcing compatibility here:
https://siteorigin.com/docs/page-builder/widget-compatibility/

**Comment by shawnhooper** [comment]
Fixed & Commited to paritywithpro14 branch
