### ISSUE TITLE
Add Read All Reviews to bottom of the widget

### ISSUE THREAD

**Issue by mathetos** [impress-org/Google-Places-Reviews#2]
Just make it a little more obvious how site visitors can see ALL the reviews rather than just going to the profile page via the title (which is sometimes hidden).

Here's one request for it:
https://wordpress.org/support/topic/number-of-reviews?replies=1

@shawnhooper per our previous conversation the text should be:
"Read all X reviews"

And it should show conditionally as follows:
- If there are no reviews it says "Be the first to write a review!" (already in place)
- If there are between one and five reviews total, the text won't appear at all
- If there are 6 or more reviews the text will appear.

**Comment by DevinWalker** [comment]
Google axes this endpoint :( closing
