### ISSUE TITLE
( ! ) Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'init_google_places_reviews_widget' not found or invalid

### ISSUE THREAD

**Issue by mathetos** [impress-org/Google-Places-Reviews#3]
This seems to come up with certain themes regardless of whether Debug is on or off. The "Medicure" theme produces this error and has been provided to @shawnhooper already.

**Comment by shawnhooper** [comment]
Tested issue does not apply to the free plugin.  

(In fact, looking at the free plugin, I can see why the error occurred in the Pro version.  It was a mistake in upgrading the Pro plugin to a Class.)

**Comment by mathetos** [comment]
OK, thanks for the confirmation.
