### ISSUE TITLE
z-index conflict with Custom Sidebars plugin by WPMUDev

### ISSUE THREAD

**Issue by mathetos** [impress-org/Google-Places-Reviews#4]
Per this ticket:
https://wordpress.org/support/topic/conflict-with-wpmudev-custom-sidebars?replies=6#post-8336346

The CSS fix is simply to add:
`
.widget-liquid-right {
    z-index: 500;
}
`

To our admin styles

**Comment by DevinWalker** [comment]
Found another incompatibility. Fixed with

```
.pac-container {
    z-index: 2147483647;
}
```
