### ISSUE TITLE
Update Readmore.js to latest version

### ISSUE THREAD

**Issue by mathetos** [impress-org/Google-Places-Reviews#8]
Lots of updates since we released this thing:
https://github.com/jedfoster/Readmore.js

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Google-Places-Reviews-Pro #56](https://github.com/WordImpress/Google-Places-Reviews-Pro/issues/56) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DevinWalker** [comment]
This functionality isn't preset in Free at this time.
